server:
  port: 8000

spring:
  main:
    allow-bean-definition-overriding: true
  #配置链路追踪
#  zipkin:
#    base-url: http://192.168.6.100:9411/
#    sender:
#      type: web

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 1000
#        readTimeout: 5000
#        retryer: com.atguigu.gmall.common.retry.MyRetryer
