#配置端口号
server:
  port: 7000
  tomcat:
    max-connections: 200 #我们的内存支持不了8000连接

spring:
  profiles:
    include: sharding  #包含的文件不用区分激活的profile
#    active: sharding,dev  #主文件 application.yaml 和激活的 application-{profile}.yaml 同时生效

  #配置链路追踪
#  zipkin:
#    base-url: http://192.168.6.100:9411/
#    sender:
#      type: web
  #mysql数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.6.100:3306/gmall_product?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
#  redis:
#    host: 192.168.6.100
#    password: chai123456

minio:
  endpoint: http://192.168.6.100:9000
  bucketName: gmall
  accessKey: admin
  secretKey: admin123456